# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDzRwcmzWwXInpBk8zvPcB3Jh8vQsVYZ
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
nome_arquivo = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[nome_arquivo]))

print("Shape:", df.shape)
print("\nColunas:", df.columns.tolist())
df.head()

import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
nome_arquivo = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[nome_arquivo]))

print("Shape:", df.shape)
print("\nColunas:", df.columns.tolist())
df.head()

# Filtrar so as fontes renovaveis do projeto
fontes = ['Eólicas', 'Solar', 'Biomassa']
df_filtrado = df[df['DscOrigemCombustivel'].isin(fontes)].copy()

# Filtrar 2020-2024
df_filtrado['DatEntradaOperacao'] = pd.to_datetime(
    df_filtrado['DatEntradaOperacao'], errors='coerce'
    )
df_filtrado = df_filtrado[
    df_filtrado['DatEntradaOperacao'].dt.year.between(2020,2024)
    ]

# Selecionar so as colunas necessarias
colunas = ['NomEmpreendimento',
           'SigUFPrincipal',
           'SigTipoGeracao',
           'DscOrigemCombustivel',
           'DscFaseUsina',
           'DatEntradaOperacao',
           'MdaPotenciaFiscalizadaKw',
           'DscMuninicpios'
           ]

df_final = df_filtrado[colunas]

print("registros apos filtro:", len(df_final))
print("\nFontes encontradas:", df_final['DscOrigemCombustivel'].unique())
df_final.head()

print(df_final['DscOrigemCombustivel'].value_counts())

for col in df.columns:
  print(col)

# Filtrar so as fontes renovaveis do projeto
fontes = ['Eólicas', 'Solar', 'Biomassa']
df_filtrado = df[df['DscOrigemCombustivel'].isin(fontes)].copy()

# Filtrar 2020-2024
df_filtrado['DatEntradaOperacao'] = pd.to_datetime(
    df_filtrado['DatEntradaOperacao'], errors='coerce'
    )
df_filtrado = df_filtrado[
    df_filtrado['DatEntradaOperacao'].dt.year.between(2020,2024)
    ]

# Selecionar so as colunas necessarias
colunas = ['NomEmpreendimento',
           'SigUFPrincipal',
           'SigTipoGeracao',
           'DscOrigemCombustivel',
           'DscFaseUsina',
           'DatEntradaOperacao',
           'MdaPotenciaFiscalizadaKw',
           'DscMuninicpios'
           ]

df_final = df_filtrado[colunas]

print("registros apos filtro:", len(df_final))
print("\nFontes encontradas:", df_final['DscOrigemCombustivel'].unique())
df_final.head()

from google.colab import files

df_final.to_excel('df_final.xlsx', index=False)
files.download('df_final.xlsx')
#

from google.colab import files

df_final.columns = [
    'NomEmpreendimento',
    'SigUFPrincipal',
    'SigTipoGeracao',
    'DscOrigemCombustivel',
    'DsFaseUsina',
    'DatEntradaOperacao',
    'MdaPoteciaFisclizadaKw',
    'DscMunicipios'
]

df_final.to_excel('dados_renovaveis_v2.xlsx', index=False)
files.download('dados_renovaveis_v2.xlsx')

# Verificar como estao os dados
print(df_final.head(2))
print("\nColunas atuais:", df_final.columns.tolist())

print(df_final['DscOrigemCombustivel'].value_counts())

import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
nome_arquivo = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[nome_arquivo]))

print("Shape:", df.shape)
print("\nColunas:", df.columns.tolist())
df.head()

# Filtrar so as fontes renovaveis do projeto
fontes = ['Eólicas', 'Solar', 'Biomassa']
df_filtrado = df[df['DscOrigemCombustivel'].isin(fontes)].copy()

# Filtrar 2020-2024
df_filtrado['DatEntradaOperacao'] = pd.to_datetime(
    df_filtrado['DatEntradaOperacao'], errors='coerce'
    )
df_filtrado = df_filtrado[
    df_filtrado['DatEntradaOperacao'].dt.year.between(2020,2024)
    ]

# Selecionar so as colunas necessarias
colunas = ['NomEmpreendimento',
           'SigUFPrincipal',
           'SigTipoGeracao',
           'DscOrigemCombustivel',
           'DsFaseUsina', # Corrected column name
           'DatEntradaOperacao',
           'MdaPoteciaFisclizadaKw', # Corrected column name
           'DscMunicipios' # Corrected column name
           ]

df_final = df_filtrado[colunas]

print("registros apos filtro:", len(df_final))
print("\nFontes encontradas:", df_final['DscOrigemCombustivel'].unique())
df_final.head()

print(df_final['DscOrigemCombustivel'].value_counts())

import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
nome_arquivo = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[nome_arquivo]))

print("Shape:", df.shape)
print("\nColunas:", df.columns.tolist())
df.head()

# Filtrar so as fontes renovaveis do projeto
fontes = ['Eólicas', 'Solar', 'Biomassa']
df_filtrado = df[df['DscOrigemCombustivel'].isin(fontes)].copy()

# Filtrar 2020-2024
df_filtrado['DatEntradaOperacao'] = pd.to_datetime(
    df_filtrado['DatEntradaOperacao'], errors='coerce'
    )
df_filtrado = df_filtrado[
    df_filtrado['DatEntradaOperacao'].dt.year.between(2020,2024)
    ]

# Selecionar so as colunas necessarias
colunas = ['NomEmpreendimento',
           'SigUFPrincipal',
           'SigTipoGeracao',
           'DscOrigemCombustivel',
           'DsFaseUsina',
           'DatEntradaOperacao',
           'MdaPoteciaFisclizadaKw', # Corrected typo here
           'DscMunicipios']

df_final = df_filtrado[colunas]

print("registros apos filtro:", len(df_final))
print("\nFontes encontradas:", df_final['DscOrigemCombustivel'].unique())
df_final.head()

for col in df_filtrado.columns:
  print(col)

from google.colab import files
df_final.to_csv('dados_renovaveis.csv', index=False, encoding='utf-8-sig')
files.download('dados_renovaveis.csv')